apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: h6ht2dbcj-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tnevrlka-rhtap/rhtap-qe-nodejs:c037234883c8de49a9f1f1766b51e4cb6d7a14fd@sha256:b14845958e869150cd297192d45323f87e9b20d564a5a7fb4d0d2bc9a0d1968e
          name: container-image
